#!/usr/bin/env bash

set -ex

FILE=$1

# Find last successful commit to master
CURL=$(curl "https://circleci.com/api/v1/project/dminnear/gitshame/tree/master")
COUNTER=0
while cat "$CURL" | jq ".[$COUNTER].outcome" |  grep -qv success; do
  let ++COUNTER
done
COMMIT=$("$CURL" | jq ".[COUNTER].vcs_revision")

if git diff --name-only "$COMMIT" | grep -q html/"$FILE" || git ls-files --others --exclude-standard | grep -q html/"$FILE"; then
  cd html/

  aws s3 cp "$FILE" s3://gitshame-html/"$FILE"
fi
