#!/usr/bin/env bash

set -ex

FILE=$1

if git diff --name-only HEAD^1 | grep -q html/"$FILE" || git ls-files --others --exclude-standard | grep -q html/"$FILE"; then
  cd html/"$FILE"

  aws s3 cp "$FILE" s3://gitshame-html/"$FILE"
fi
