#!/usr/bin/env bash

set -ex

NAME=$1

if git diff --name-only origin/master | grep -q lambdas/"$NAME"; then
  cd lambdas/"$NAME"
  zip -r "$NAME" .

  aws s3 cp "$NAME".zip s3://gitshame-lambdas/"$NAME".zip
  aws lambda update-function-code --function-name "$NAME" --region="us-east-1" --s3-bucket "gitshame-lambdas" --s3-key "$NAME".zip
fi
